trigger:
- master
- features/*

jobs:

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 2.x SDK for testing'
    inputs:
      packageType: 'sdk'
      version: '2.x'
  - task: UseDotNet@2
    displayName: 'Install main .NET Core SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: PowerShell@2
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.ps1